variables:
  UTEST_COMPILE_FIRST: "yes"
  UTEST_TEST_COV_CMD: "make coverage"
  DOC_GEN_CMD: "make doc"
  BUILD_TARGET: libamxo
  BUILD_DEPS: libamxc=1.7.0 libamxd=3.6.12 libamxp=0.10.2 flex bison
  TEST_DEPS: valgrind
  SAH_NTE_IMAGE: $SAH_CI_IMAGE

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
