variables:
  UTEST_COMPILE_FIRST: "yes"
  UTEST_TEST_COV_CMD: "make coverage"
  DOC_GEN_CMD: "make doc"
  BUILD_TARGET: libamxo
  BUILD_DEPS: libamxc=1.4.2 libamxd=3.2.10 libamxp=0.9.10 flex bison

include:
  - remote: 'https://gitlab.com/soft.at.home/ci/gitlab-ci/raw/main/ambiorix-default-pipeline.yml'
